### ISSUE TITLE
CMD to add Git in building container

### ISSUE THREAD

**Issue by kenwan12** [Microsoft/dotnet-framework-docker-samples#5]
I would like to see if we can use CMD to install Git to our own image ?

For example :

WORKDIR /app
CMD '.\Git-2.10.2-64-bit.exe /silent /suppressmsgboxes /dir="c:\git64" /log="git64.log"' ?

Or we can add the Git  exe to the container and run
the silent installation after starting the container ?

Thanks

Ken

**Comment by MichaelSimons** [comment]
@kenwan12, IMHO it would make more sense to install git in your own image (e.g. Dockerfile) rather than the running container.  The benefit of installing it in the image is that the installation overhead is occurred only once vs every time the image is run.  

I noticed AppVeyor has a WindowsServerCore image that includes Git -https://github.com/appveyor/docker/tree/master/images/git  This may be a good reference for you.

**Comment by kenwan12** [comment]
Thanks.

Would explore if I can install Git onto the microsoft/dotnet-framework image.

Cheers

Ken
